// <auto-generated />
using System;
using GestionDisponibilite.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GestionDisponibilite.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250508061917_UpdateAdresse")]
    partial class UpdateAdresse
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GestionDisponibilite.Model.Employe", b =>
                {
                    b.Property<Guid>("EmployeID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Adresse")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly>("DateDeNaissance")
                        .HasColumnType("date");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Prenom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Qualitifactions")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("SurProjet")
                        .HasColumnType("bit");

                    b.Property<string>("Telephone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EmployeID");

                    b.ToTable("Employes");
                });

            modelBuilder.Entity("GestionDisponibilite.Model.EmployeProjet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("EmployeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ProjetId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("EmployeId");

                    b.HasIndex("ProjetId");

                    b.ToTable("EmployeProjets");
                });

            modelBuilder.Entity("GestionDisponibilite.Model.Projet", b =>
                {
                    b.Property<Guid>("ProjetId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Client")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly>("DebutProjet")
                        .HasColumnType("date");

                    b.Property<DateOnly>("FinProjet")
                        .HasColumnType("date");

                    b.Property<string>("NomDuProjet")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ProjetId");

                    b.ToTable("Projets");
                });

            modelBuilder.Entity("GestionDisponibilite.Model.EmployeProjet", b =>
                {
                    b.HasOne("GestionDisponibilite.Model.Employe", "Employe")
                        .WithMany("EmployeProjets")
                        .HasForeignKey("EmployeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GestionDisponibilite.Model.Projet", "Projet")
                        .WithMany("EmployeProjets")
                        .HasForeignKey("ProjetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employe");

                    b.Navigation("Projet");
                });

            modelBuilder.Entity("GestionDisponibilite.Model.Employe", b =>
                {
                    b.Navigation("EmployeProjets");
                });

            modelBuilder.Entity("GestionDisponibilite.Model.Projet", b =>
                {
                    b.Navigation("EmployeProjets");
                });
#pragma warning restore 612, 618
        }
    }
}
